{ moduleWithSystem, ... }:
let
  # Replacing pkgs.fish is what makes the login shell and /etc/shells pick up
  # the wrapped build; users.users.<name>.shell would otherwise get the plain
  # one and none of the above would load at login. No recursion: the wrapper is
  # built from perSystem's pkgs, which this overlay does not touch.
  fishOverlay = moduleWithSystem (
    { self', ... }:
    {
      nixpkgs.overlays = [ (_: _: { fish = self'.packages.fish; }) ];
    }
  );
in
{
  # The wrapper carries only what is portable — the greeting, key bindings and
  # the plugin. Everything else fish does here is generated by other
  # Home Manager modules (atuin, direnv, zoxide, fzf, ghostty, completions)
  # into config.fish, so programs.fish stays enabled below rather than being
  # replaced; it is the integration point those modules write through.
  #
  # Nothing here may name another component. A function that drives one
  # belongs to that component's own module — see `shellHooks` below.
  flake.wrappers.fish =
    {
      wlib,
      pkgs,
      lib,
      ...
    }:
    let
      inherit (pkgs.stdenv.hostPlatform) isDarwin;
    in
    {
      imports = [ wlib.wrapperModules.fish ];

      # The wrapper defaults to --no-config, which makes fish skip
      # ~/.config/fish/config.fish altogether. That file is where atuin,
      # direnv, zoxide, fzf, ghostty, starship and the generated completions
      # all install themselves, so leaving it on silently removes every one of
      # them and drops the prompt back to fish's default.
      flags."--no-config" = false;

      plugins = [ { src = pkgs.fishPlugins.plugin-sudope; } ];

      shellAliases = {
        gen = "nix-env --list-generations";
      }
      // lib.optionalAttrs isDarwin {
        unb = "xattr -d com.apple.quarantine";
      };

      # Sourced through --init-command, which runs before any interactive
      # config. Only settings that must exist before the first prompt live
      # here; everything callable is an autoloaded function instead.
      configFile.content = ''
        set -g fish_greeting ""
        fish_vi_key_bindings
        ${lib.optionalString isDarwin ''
          # Casks with a CLI symlink it in here, so every Homebrew-delivered AI
          # tool is invisible without this.
          fish_add_path /opt/homebrew/bin
        ''}
      '';
    };

  # One module in both systems: `system/user.nix` and `darwin/user.nix` both
  # set the login shell to pkgs.fish, and nothing in the overlay is per-platform.
  flake.nixosModules.fish = fishOverlay;
  flake.darwinModules.fish = fishOverlay;

  # The contract between `update`/`reb` and the components they drive. Loaded
  # through home-manager's sharedModules rather than the fish bundle, so an app
  # can register a hook without the host having taken `shell` — an undeclared
  # option here would be an eval error a long way from its cause.
  flake.homeModules.shellHooks =
    { lib, ... }:
    {
      options.shellHooks = {
        update = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [ ];
          example = [ "update-ai-clis" ];
          description = ''
            Pin updaters `update` runs before relocking. Each is run in turn and
            the first failure aborts, so nothing relocks on a half-updated pin.
          '';
        };
        rebPostSwitch = lib.mkOption {
          type = lib.types.lines;
          default = "";
          description = ''
            Fish run by `reb` after a successful switch and before the
            checkpoint commit. For units a switch cannot restart itself.
          '';
        };
      };
    };

  flake.homeModules.fish = moduleWithSystem (
    { self', ... }:
    {
      pkgs,
      lib,
      config,
      ...
    }:
    let
      inherit (pkgs.stdenv.hostPlatform) isDarwin;

      # Skipped entirely when no component registered one, since fish rejects
      # an empty block.
      updateTools = lib.optionalString (config.shellHooks.update != [ ]) ''
        if test (count $argv) -eq 0
            ${lib.concatMapStringsSep "\n    " (c: "${c}; or return 1") config.shellHooks.update}
        end
      '';
    in
    {
      programs.fish = {
        enable = true;
        package = self'.packages.fish;

        functions = {
          # `update` relocks everything and runs whatever pin updaters this host
          # installed; `update nvf` (or any input names) relocks only those and
          # skips the updaters, which is the narrow diff worth having when one
          # input needs to move. --commit-lock-file keeps the relock as its own
          # commit, so reb's checkpoint no longer bundles a lock bump with
          # unrelated edits.
          update.body = ''
            ${updateTools}
            nix flake update --flake ~/nixos-config --commit-lock-file $argv
          '';

          reb.body = ''
            # `nh os` drives NixOS, `nh darwin` drives nix-darwin; everything
            # else about a rebuild is the same on both.
            # The flake attribute and the hostname are the same word on every
            # NixOS host here, so this needs no per-host branch. darwin is the
            # exception: its hostName is MacBook-Pro.
            set -l target ${if isDarwin then "darwin" else "$hostname"}
            set -l platform ${if isDarwin then "darwin" else "os"}
            set -l repo ~/nixos-config
            if test (count $argv) -gt 0; set target $argv[1]; end

            # A flake build cannot see untracked files, so an unstaged new module is
            # silently skipped.
            git -C $repo add -A
            ${lib.optionalString isDarwin ''
              # Auto-remove rogue standalone binary left by agy background self-updater
              # before brew bundle runs to prevent cask symlink collisions.
              if test -f /opt/homebrew/bin/agy -a ! -L /opt/homebrew/bin/agy
                  rm -f /opt/homebrew/bin/agy
              end
            ''}
            # nh elevates itself, so no sudo here.
            if nh $platform switch $repo -H $target -- --impure
                ${config.shellHooks.rebPostSwitch}
                # Checkpoint commit for rollback, not a real message — reword if the
                # change deserves one.
                if not git -C $repo diff --cached --quiet
                    git -C $repo commit -q -m "rebuild "(date '+%Y-%m-%d %H:%M:%S')
                    echo "Committed as "(git -C $repo rev-parse --short HEAD)
                end
            else
                echo "Rebuild failed. Changes are staged but not committed."
                return 1
            end
          '';
        };
      };
    }
  );
}
