{ moduleWithSystem, ... }:
let
  # Replacing pkgs.fish is what makes the login shell and /etc/shells pick up
  # the wrapped build; users.users.<name>.shell would otherwise get the plain
  # one and none of the above would load at login. No recursion: the wrapper is
  # built from perSystem's pkgs, which this overlay does not touch.
  fishOverlay = moduleWithSystem (
    { self', ... }:
    {
      nixpkgs.overlays = [ (_: _: { fish = self'.packages.fish; }) ];
    }
  );
in
{
  # The wrapper carries only what is portable — aliases, functions, greeting,
  # key bindings, plugin. Everything else fish does here is generated by other
  # Home Manager modules (atuin, direnv, zoxide, fzf, ghostty, completions)
  # into config.fish, so programs.fish stays enabled below rather than being
  # replaced; it is the integration point those modules write through.
  flake.wrappers.fish =
    {
      wlib,
      pkgs,
      lib,
      ...
    }:
    let
      inherit (pkgs.stdenv.hostPlatform) isLinux isDarwin;
    in
    {
      imports = [ wlib.wrapperModules.fish ];

      # The wrapper defaults to --no-config, which makes fish skip
      # ~/.config/fish/config.fish altogether. That file is where atuin,
      # direnv, zoxide, fzf, ghostty, starship and the generated completions
      # all install themselves, so leaving it on silently removes every one of
      # them and drops the prompt back to fish's default.
      flags."--no-config" = false;

      plugins = [ { src = pkgs.fishPlugins.plugin-sudope; } ];

      # niri is deliberately not referenced by store path: perSystem's nixpkgs
      # has no libdisplay-info overlay, so pulling it in here fails the build.
      # The android function only runs inside a niri session anyway.
      runtimePkgs = [ pkgs.jq ];

      shellAliases = {
        # macOS installs LibreOffice as an .app, which has no CLI entry point.
        word = if isDarwin then "open -a LibreOffice --args --writer" else "libreoffice --writer";
        powerpoint = if isDarwin then "open -a LibreOffice --args --impress" else "libreoffice --impress";
        gen = "nix-env --list-generations";
        wt = "git worktree list";
        wta = "git worktree add";
        wtr = "git worktree remove";
        v = "nvim";
        vi = "nvim";
        vim = "nvim";
        tree = "eza --tree --icons";
        ll = "eza -la --icons --group-directories-first --header --git-ignore";
        pf = "pass-find";
      }
      // lib.optionalAttrs isDarwin {
        unb = "xattr -d com.apple.quarantine";
      };

      # No `functions` option upstream, so these are defined inline. Sourced
      # through --init-command, which runs before any interactive config.
      configFile.content = ''
        set -g fish_greeting ""
        fish_vi_key_bindings
        ${lib.optionalString isDarwin ''
          # Casks with a CLI symlink it in here, so every Homebrew-delivered AI
          # tool is invisible without this.
          fish_add_path /opt/homebrew/bin
        ''}

        # `update` relocks everything and bumps the pinned tools; `update nvf` (or
        # any input names) relocks only those and skips the tool updaters, which
        # is the narrow diff worth having when one input needs to move.
        # --commit-lock-file keeps the relock as its own commit, so reb's
        # checkpoint no longer bundles a lock bump with unrelated edits.
        function update
            if test (count $argv) -eq 0
                ${lib.optionalString isLinux "update-brave-origin; and "}update-ai-clis
                or return 1
            end
            nix flake update --flake ~/nixos-config --commit-lock-file $argv
        end

        ${lib.optionalString isLinux ''
          # Android VM, sized to the monitor it opens on. Must be the *logical*
          # size, used as niri reports it — do not divide by the scale again. A
          # mismatch does not letterbox the picture, it scales every click, since
          # qemu maps pointer position by proportion.
          function android
              set -l state ~/.local/share/waydroid-vm

              # The external monitor if attached, otherwise whichever output has focus.
              set -l output
              if niri msg -j outputs | jq -e 'has("HDMI-A-1")' >/dev/null 2>&1
                  set output (niri msg -j outputs | jq -c '."HDMI-A-1"')
              else
                  set output (niri msg -j focused-output)
              end

              set -l size (printf '%s' "$output" | jq -er '.logical | "\(.width) \(.height)"' | string split ' ')
              if test (count $size) -ne 2
                  echo "Could not read the monitor size from niri."
                  return 1
              end

              # The disk image lives in the working directory; running this anywhere
              # else starts a blank Android and re-downloads 1.6 GB.
              mkdir -p $state
              cd $state
              or return 1

              set -x QEMU_OPTS "-device virtio-gpu-gl-pci,xres=$size[1],yres=$size[2] -display gtk,gl=on,show-menubar=off -full-screen"
              nix run ~/nixos-config#nixosConfigurations.waydroid.config.system.build.vm
          end
        ''}

        function reb
            # `nh os` drives NixOS, `nh darwin` drives nix-darwin; everything
            # else about a rebuild is the same on both.
            set -l target ${if isDarwin then "darwin" else "asahi"}
            set -l platform ${if isDarwin then "darwin" else "os"}
            set -l repo ~/nixos-config
            if test (count $argv) -gt 0; set target $argv[1]; end

            # A flake build cannot see untracked files, so an unstaged new module is
            # silently skipped.
            git -C $repo add -A

            # nh elevates itself, so no sudo here.
            if nh $platform switch $repo -H $target -- --impure
                # Checkpoint commit for rollback, not a real message — reword if the
                # change deserves one.
                if not git -C $repo diff --cached --quiet
                    git -C $repo commit -q -m "rebuild "(date '+%Y-%m-%d %H:%M:%S')
                    echo "Committed as "(git -C $repo rev-parse --short HEAD)
                end
            else
                echo "Rebuild failed. Changes are staged but not committed."
                return 1
            end
        end

        function pass-find
            if not pass-cli test >/dev/null 2>&1
                pass-cli test
                or return 1
            end
            pass-cli item list Personal --output json | jq -r '(.items // .)[] | "[\((.item_type // .itemType // .type // "unknown") | ascii_upcase)] \(.title // .name)\t\(.id // .item_id // .itemId)"' | fzf --ansi --header="Select an item to view credentials" --with-nth=1 | string split \t | read -l display_name id
            if test -n "$id"
                pass-cli item view --vault-name Personal --item-id $id
            end
        end
      '';
    };

  # One module in both systems: `system/user.nix` and `darwin/user.nix` both
  # set the login shell to pkgs.fish, and nothing in the overlay is per-platform.
  flake.nixosModules.fish = fishOverlay;
  flake.darwinModules.fish = fishOverlay;

  flake.homeModules.fish = moduleWithSystem (
    { self', ... }:
    {
      programs.fish = {
        enable = true;
        package = self'.packages.fish;
      };
    }
  );
}
